lib: [
  "_build/install/default/lib/stat_lang/META"
  "_build/install/default/lib/stat_lang/ast.ml"
  "_build/install/default/lib/stat_lang/dune-package"
  "_build/install/default/lib/stat_lang/interpreter.a"
  "_build/install/default/lib/stat_lang/interpreter.cma"
  "_build/install/default/lib/stat_lang/interpreter.cmi"
  "_build/install/default/lib/stat_lang/interpreter.cmt"
  "_build/install/default/lib/stat_lang/interpreter.cmx"
  "_build/install/default/lib/stat_lang/interpreter.cmxa"
  "_build/install/default/lib/stat_lang/interpreter.ml"
  "_build/install/default/lib/stat_lang/interpreter__.cmi"
  "_build/install/default/lib/stat_lang/interpreter__.cmt"
  "_build/install/default/lib/stat_lang/interpreter__.cmx"
  "_build/install/default/lib/stat_lang/interpreter__.ml"
  "_build/install/default/lib/stat_lang/interpreter__Ast.cmi"
  "_build/install/default/lib/stat_lang/interpreter__Ast.cmt"
  "_build/install/default/lib/stat_lang/interpreter__Ast.cmx"
  "_build/install/default/lib/stat_lang/interpreter__Lexer.cmi"
  "_build/install/default/lib/stat_lang/interpreter__Lexer.cmt"
  "_build/install/default/lib/stat_lang/interpreter__Lexer.cmx"
  "_build/install/default/lib/stat_lang/interpreter__Parser.cmi"
  "_build/install/default/lib/stat_lang/interpreter__Parser.cmt"
  "_build/install/default/lib/stat_lang/interpreter__Parser.cmti"
  "_build/install/default/lib/stat_lang/interpreter__Parser.cmx"
  "_build/install/default/lib/stat_lang/lexer.ml"
  "_build/install/default/lib/stat_lang/opam"
  "_build/install/default/lib/stat_lang/parser.ml"
  "_build/install/default/lib/stat_lang/parser.mli"
]
libexec: [
  "_build/install/default/lib/stat_lang/interpreter.cmxs"
]
bin: [
  "_build/install/default/bin/stat_lang"
]
doc: [
  "_build/install/default/doc/stat_lang/README.md"
]
