name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install OCaml and Dependencies
      run: |
        opam init --auto-setup --disable-sandboxing
        eval $(opam env)

    - name: Build and Run Tests
      run: |
        dune runtest
